---
- name: Crear VMware Snapshot
  hosts: W10-01
  gather_facts: false

  tasks:
    - name: Crear snapshot
      vmware_guest_snapshot:
        validate_certs: no
        name: "{{ inventory_hostname }}"
        state: present
        description: "Snapshot created by Ansible Tower"

