---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Deploy y Personalizacion
    vmware_guest:
      validate_certs: False
      name: ARSRV-TEST-ANSIBLE
      template: W2019-v22.06
      datacenter: "CIP Ezeiza"
      folder: "/CIP Ezeiza/Cluster vSAN"
      state: poweredon
      customization_spec: "Windows Server 2022"
      cluster: LAB
      wait_for_ip_address: yes

